name: Deploy Docs

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release
  WORKING_DIR: server

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.WORKING_DIR }}
    - name: Generate Prisma docs
      run: npx prisma-docs-generator --out-dir docs/prisma
      working-directory: ${{ env.WORKING_DIR }}
    - name: Generate Node.js docs
      run: npx jsdoc -c jsdoc.json
      working-directory: ${{ env.WORKING_DIR }}
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
      working-directory: ${{ env.WORKING_DIR }}
